# Generated by Django 5.1.2 on 2024-11-12 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopt',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='volunteers',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
